import ThemeContextProvider from "@/utils/themes";

import type { Metadata } from "next";
import "./globals.css";



export const metadata: Metadata = {
  title: "Abdullah Muaz | Front-End Developer Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
       <ThemeContextProvider>
          {children}
        </ThemeContextProvider>
      </body>
    </html>
  );
}
